
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: flask  # Replace with your desired namespace
  labels:
    app: flask-app
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80  # The port that the service will expose
      targetPort: 5000  # The port that the container is listening on

